<?php declare(strict_types=1);

namespace WeDevelop\Audit;

use Symfony\Component\Translation\TranslatableMessage;
use Symfony\Contracts\Translation\TranslatableInterface;

interface RenderAuditLogInterface extends TranslatableInterface
{
    public const TRANSLATION_DOMAIN = 'audit';
    public const TRANSLATION_NAMESPACE_ACTION = 'action';
    public const TRANSLATION_NAMESPACE_CONTEXT = 'source';
    public const TRANSLATION_NAMESPACE_EXTRA = 'info';

    public function getMessage(): string;

    /** @return array<string, string> */
    public function getParameters(): array;

    /**
     * Return a list of additional pieces of information that compliment the
     * main audit log message (for example, this could state what the old value
     * was and what it was changed to).
     *
     * The information generated by this method will most likely be constructed
     * from the extra/additional data from AuditDataInterface::getData(),
     * however it should not fail if certain pieces, or all, of the expected
     * data is missing.
     *
     * @return iterable<string|TranslatableMessage>
     */
    public function getInfo(): iterable;
}
